# Generated by Django 5.1.4 on 2025-01-04 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundRemoverResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_name', models.CharField(max_length=255)),
                ('original_image', models.BinaryField()),
                ('processed_image', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_remover_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Background remover results',
                'db_table': 'background_remover_results',
            },
        ),
    ]
