# Generated by Django 5.1.4 on 2024-12-27 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed.', regex='^[a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed.', regex='^[a-zA-Z\\s]*$')]),
        ),
    ]
